# config.toml
# 配置文件示例
debug = true
# eid, fp参数必须填写，具体请参考 wiki-常见问题
# 随意填写可能导致订单无法提交等问题
eid = ""
fp = ""
# 商品id
sku_id = "100012043978"
# 抢购数量
seckill_num = 1
# 设定时间 # 2020-12-09 10:00:00.100000
buy_time = "2021-03-30 14:59:59"
# 默认UA
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

# zap 配置
[logger]
    # zap 环境配置
    env = "dev"
    # 日志级别 debug,info,warn,error,fatal
    level = "debug"

#账号信息
[account]
    # 支付密码
    # 如果你的账户中有可用的京券（注意不是东券）或 在上次购买订单中使用了京豆，
    # 那么京东可能会在下单时自动选择京券支付 或 自动勾选京豆支付。
    # 此时下单会要求输入六位数字的支付密码。请在下方配置你的支付密码，如 123456 。
    # 如果没有上述情况，下方请留空。
    payment_pwd = ""

#消息推送
[messenger]
    # 开启推送服务
    enable = false
    # 目前只支持smtp邮箱推送
    type = "smtp"
    # 消息接收人
    email = ""

#smtp配置
# 开启smtp消息推送必须填入 email_user、email_pwd，email_host 若不填则会自动判断，email_pwd 如何获取请自行百度。
[smtp]
    # 邮箱域名 smtp.xx.com
    email_host = ""
    # 通信端口
    port = "456"
    # 邮箱地址 xxxxxxxx@xx.com
    email_user = ""
    # 邮箱授权码（并不一定是邮箱密码） xxxxxxxxxxxxxxxx
    email_pwd = ""